name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - 24
    container:
      image: erlang:${{ matrix.otp }}

    steps:
    - uses: actions/checkout@v3
    - name: Compile and run tests
      env:
        BUILD_WITHOUT_QUIC: "true"
      run: make
