name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - "25.1.2-3"
        os:
          - ubuntu20.04
    container:
      image: ghcr.io/emqx/emqx-builder/5.0-34:1.13.4-${{ matrix.otp }}-${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install additional packages
      run: |
        apt-get update
        apt-get install -y openjdk-11-jdk asciidoctor xsltproc docbook-xsl
    - name: Compile and run tests
      env:
        BUILD_WITHOUT_QUIC: "true"
      run: |
        git config --global --add safe.directory $(pwd)
        make all docs
    - name: Create release package
      shell: bash
      run: |
        make release
    - if: failure()
      run: cat rebar3.crashdump
    - run: ./_build/default/bin/emqttb
    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: ./*.tar.gz
