name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - "24.3.4.2-1"
    container:
      image: ghcr.io/emqx/emqx-builder/5.0-27:1.13.4-${{ matrix.otp }}-debian11

    steps:
    - uses: actions/checkout@v3
    - name: Compile and run tests
      env:
        BUILD_WITHOUT_QUIC: "true"
      run: make
